{{- if .Values.prosody.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "jitsi-meet.name-prosody" . }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name:  {{ include "jitsi-meet.name-prosody" . }}
  maxReplicas: {{ .Values.prosody.hpa.maxReplicas }}
  minReplicas: {{ .Values.prosody.hpa.minReplicas }}
{{- end }}
